AWSTemplateFormatVersion: '2010-09-09'
Description: 'description'
Metadata:
  Version: 1
Parameters:
  CustomerAccountId:
    Description: The Customer Account ID
    MinLength: 36
    MaxLength: 36
    Type: String
    Default: accountId
  Stage:
    Description: stage
    MinLength: 1
    MaxLength: 12
    Type: String
    Default: MyStage

Resources:
  NewCustomerLambdaFunction:
      Type: "AWS::Lambda::Function"
      Properties:
        Handler: "python_new_file_handler.lambda_handler"
        FunctionName: MyFunctionName
        Code:
          S3Bucket: "lambda-functions"
          S3Key: "amilookup.zip"
        Runtime: "python3.7"
        Timeout: 25
        TracingConfig:
          Mode: "Active"

