AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa Skill https://developer.amazon.com/alexa-skills-kit
Resources:
  AlexaSkillFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: inputs/alexa_skill
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill


Metadata:
  Protego:
    Functions:
      AlexaSkillFunction:
        Features:
          PermissiveRole:
            Enabled: false
